name: Update Slack on catalog.yaml changes

env:
  TOKEN: ${{secrets.SLACK_TOKEN.token}}

on:
  push:
    branches:
      - main

jobs:
  update-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and run app.js
        run: |
          echo "$env:TOKEN"
          npm i
          node api
